name: ftk_template_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  logger: ^2.6.0
  flutter:
    sdk: flutter
  ftk_ui:
    git:
      url: https://github.com/NSRitz999/ftk_ui.git
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_themes: ^0.3.15
  smb_connect: ^0.0.9

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-Bold.ttf
